version: '3.8'

services:
  billbridge-backend:
    build: 
      context: ./backend
    ports:
      - "8180:8080"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - shared-bridge

  db:
    image: postgres:15
    container_name: billbridge-db
    ports:
      - "5433:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - billbridge_data:/var/lib/postgresql/data
    networks:
      - shared-bridge

volumes:
  billbridge_data:

networks:
  shared-bridge:
    external: true 