version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    ports:
      - "8180:8080"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - billbridge-network

  db:
    image: postgres:15
    ports:
      - "5433:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - billbridge-network

volumes:
  postgres_data:

networks:
  billbridge-network:
    driver: bridge 